In [8]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from statsmodels.formula.api import ols
from sklearn.model_selection import train_test_split
%matplotlib inline

In [9]:
df = pd.read_csv('KC_Initial_Clean.csv')
df

,Unnamed: 0,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,Tour_Rating,...,98146,98148,98155,98166,98168,98177,98178,98188,98198,98199
0,0,2014-10-13,221900.0,3,1.00,1180,5650,1.0,0.0,0.0,...,0,0,0,0,0,0,1,0,0,0
1,1,2014-12-09,538000.0,3,2.25,2570,7242,2.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
2,2,2015-02-25,180000.0,2,1.00,770,10000,1.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
3,3,2014-12-09,604000.0,4,3.00,1960,5000,1.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
4,4,2015-02-18,510000.0,3,2.00,1680,8080,1.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21592,21592,2014-05-21,360000.0,3,2.50,1530,1131,3.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
21593,21593,2015-02-23,400000.0,4,2.50,2310,5813,2.0,0.0,0.0,...,1,0,0,0,0,0,0,0,0,0
21594,21594,2014-06-23,402101.0,2,0.75,1020,1350,2.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
21595,21595,2015-01-16,400000.0,3,2.50,1600,2388,2.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
21596,21596,2014-10-15,325000.0,2,0.75,1020,1076,2.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0

In [12]:
lr_model = ols(formula='price~bedrooms', data=df).fit()

In [13]:
lr_model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.095
Model:                            OLS   Adj. R-squared:                  0.095
Method:                 Least Squares   F-statistic:                     2276.
Date:                Wed, 27 Nov 2019   Prob (F-statistic):               0.00
Time:                        16:29:08   Log-Likelihood:            -3.0631e+05
No. Observations:               21597   AIC:                         6.126e+05
Df Residuals:                   21595   BIC:                         6.126e+05
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   1.272e+05   8979.293     14.166      0.000     1.1e+05    1.45e+05
bedrooms    1.225e+05   2566.930     47.709      0.000    1.17e+05    1.27e+05
==============================================================================
Omnibus:                    18831.341   Durbin-Watson:                   1.961
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          1195104.832
Skew:                           3.900   Prob(JB):                         0.00
Kurtosis:                      38.598   Cond. No.                         14.2
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""